version: 2
jobs:
  build:
    docker:
      - image: cimg/node:18.18

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn test

      - run:
          name: npm pack
          command: |
            mkdir -p artifacts
            yarn pack
            mv eslint-config-ustudio-*.tgz artifacts/

      - store_artifacts:
          path: artifacts
