version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.18.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-{{ checksum "package.json" }}-
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

      - run: npm test

      - run:
          name: npm pack
          command: |
            mkdir -p artifacts
            npm pack
            mv eslint-config-ustudio-*.tgz artifacts/

      - store_artifacts:
          path: artifacts

workflows:
  version: 2
  build:
    jobs:
      - build
